# Conexion a MongoDB en AWS EC2:
spring.mongodb.host=44.211.11.219
spring.mongodb.port=27017
spring.mongodb.database=theca_db
spring.mongodb.authentication-database=admin
spring.mongodb.username=theca_user
spring.mongodb.password=${MONGO_PASSWORD}

# Puerto del servidor:
server.port=8080

# Configuracion de JWT:
theca.app.jwtSecret=${JWT_SECRET}
theca.app.jwtExpirationMs=86400000

# Configuracion de logging:
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

# Configuracion de zona horaria para fechas y horas:
spring.jackson.time-zone=Europe/Madrid

# Configuracion de AWS S3:
# Compatible con multiples modos:
aws.profile=${AWS_PROFILE:default}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.s3.url-expiration-minutes=10

# Credenciales directas (para CI/CD):
aws.access-key-id=${AWS_ACCESS_KEY_ID:}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:}
aws.session-token=${AWS_SESSION_TOKEN:}